### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous block remove!

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#1108]
```
[18:06:46] [pool-5-thread-23/WARN]: java.lang.IllegalStateException: Asynchronous block remove!
[18:06:46] [pool-5-thread-23/WARN]:     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[18:06:46] [pool-5-thread-23/WARN]:     at net.minecraft.server.v1_12_R1.Block.remove(Block.java:323)
[18:06:46] [pool-5-thread-23/WARN]:     at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:473)
[18:06:46] [pool-5-thread-23/WARN]:     at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378)
[18:06:46] [pool-5-thread-23/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:145)
[18:06:46] [pool-5-thread-23/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeId(CraftBlock.java:132)
[18:06:46] [pool-5-thread-23/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:123)
[18:06:46] [pool-5-thread-23/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setType(CraftBlock.java:118)
[18:06:46] [pool-5-thread-23/WARN]:     at com.github.unchama.util.effect.BukkitResources$.$anonfun$vanishingBlockSetResource$4(BukkitResources.scala:16)
[18:06:46] [pool-5-thread-23/WARN]:     at com.github.unchama.util.effect.BukkitResources$.$anonfun$vanishingBlockSetRes
ource$4$adapted(BukkitResources.scala:16)
[18:06:46] [pool-5-thread-23/WARN]:     at scala.collection.immutable.HashSet.foreach(HashSet.scala:932)
[18:06:46] [pool-5-thread-23/WARN]:     at com.github.unchama.util.effect.BukkitResources$.$anonfun$vanishingBlockSetResource$3(BukkitResources.scala:16)
[18:06:46] [pool-5-thread-23/WARN]:     at fromFuture @ com.github.unchama.seichiassist.infrastructure.redisbungee.RedisBungeeNetworkConnectionCount.<init>(RedisBungeeNetworkConnectionCount.scala:60)
[18:06:46] [pool-5-thread-23/WARN]:     at >>$extension @ fs2.Stream$.$anonfun$merge$5(Stream.scala:1876)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.seichiassist.util.BreakUtil$.$anonfun$massBreakBlock$9(BreakUtil.scala:362)
[18:06:46] [pool-5-thread-23/WARN]:     at map @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$9(OnBukkitServerThread.scala:50)
[18:06:46] [pool-5-thread-23/WARN]:     at cancelable @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$5(OnBukkitServerThread.scala:35)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$5(OnBukkitServerThread.scala:29)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.runAction(OnBukkitServerThread.scala:25)
[18:06:46] [pool-5-thread-23/WARN]:     at map @ com.github.unchama.seichiassist.util.BreakUtil$.massBreakBlock(BreakUtil.scala:325)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.seichiassist.util.BreakUtil$.massBreakBlock(BreakUtil.scala:325)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.seichiassist.seichiskill.effect.ActiveSkillNormalEffect.runBreakEffect(ActiveSkillEffect.scala:115)
[18:06:46] [pool-5-thread-23/WARN]:     at map @ com.github.unchama.seichiassist.listener.PlayerBlockBreakListener.$anonfun$onPlayerActiveSkillEvent$17(PlayerBlockBreakListener.scala:198)
[18:06:46] [pool-5-thread-23/WARN]:     at map @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$9(OnBukkitServerThread.scala:50)
[18:06:46] [pool-5-thread-23/WARN]:     at cancelable @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$5(OnBukkitServerThread.scala:35)
[18:06:46] [pool-5-thread-23/WARN]:     at flatMap @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$5(OnBukkitServerThread.scala:29)
```

**Comment by kory33** [comment]
related: #1078
