### ISSUE TITLE
各種メニューのページ送り・戻りが不可

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#117]
以下、エラー抜粋。

```
Caused by: java.lang.NullPointerException
	at com.github.unchama.seichiassist.listener.PlayerInventoryListener.onPlayerClickStickMenuEvent(PlayerInventoryListener.java:183) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 15 more
```

```
Caused by: java.lang.NullPointerException
	at com.github.unchama.seichiassist.listener.PlayerInventoryListener.onPlayerClickMineStackMainMenuEvent(PlayerInventoryListener.java:1727) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 15 more
```

**Comment by KisaragiEffective** [comment]
ｶﾞｯ

**Comment by unchama** [comment]
ガッ
原因分かります……？

**Comment by karayuumac** [comment]
UUID取得に変えてから表示されなくなってる気がします(あくまで気がするなのですが)

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/5a0436fe5173b34230c28d87ef087e6ab683d015/src/main/java/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java#L183

https://github.com/GiganticMinecraft/SeichiAssist/blob/5a0436fe5173b34230c28d87ef087e6ab683d015/src/main/java/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java#L1727

もしかすると#getOwningPlayerのところでコケてるのかもしれません (要調査)

**Comment by kory33** [comment]
closed by #132.
