### ISSUE TITLE
subhome setができない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1184]
```
[Sun, 3. Oct 2021 15:27:23 JST ERROR] [SQL Execution Failed] insert into seichiassist.sub\_home (player\_uuid, server\_id, id, name, location\_x, location\_y, location\_z, world\_name) values ('9eb55077-a9c1-4a88-a22b-e6651fabcc6e', 1, 0, null, -14, 74, 630, 'world\_SW') on duplicate key update name = values(null), location\_x = values(-14), location\_y = values(74), location\_z = values(630), world\_name = values('world\_SW') (Reason: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'null),
      location\_x = values(-14),
      location\_y = values(74),
      loca' at line 5)
[Sun, 3. Oct 2021 15:27:23 JST INFO] Caught exception while executing subhome command.
[Sun, 3. Oct 2021 15:27:23 JST WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'null),
      location\_x = values(-14),
      location\_y = values(74),
      loca' at line 5
[Sun, 3. Oct 2021 15:27:23 JST WARN] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.Util.getInstance(Util.java:408)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeUpdate(DBConnectionAttributesWiredPreparedStatement.scala:80)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at scalikejdbc.StatementExecutor.$anonfun$executeUpdate$1(StatementExecutor.scala:400)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at >>$extension @ fs2.Stream$.$anonfun$merge$5(Stream.scala:1876)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.seichiassist.subsystems.subhome.domain.SubHomePersistence.$anonfun$upsertLocation$3(SubHomePersistence.scala:47)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at >>$extension @ fs2.Stream$.$anonfun$merge$5(Stream.scala:1876)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.seichiassist.subsystems.subhome.domain.SubHomePersistence.get(SubHomePersistence.scala:35)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.seichiassist.subsystems.subhome.domain.SubHomePersistence.upsertLocation(SubHomePersistence.scala:45)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.seichiassist.subsystems.subhome.domain.SubHomePersistence.upsertLocation(SubHomePersistence.scala:45)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.seichiassist.subsystems.subhome.bukkit.command.SubHomeCommand$.$anonfun$setExecutor$2(SubHomeCommand.scala:121)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.seichiassist.subsystems.subhome.bukkit.command.SubHomeCommand$.$anonfun$setExecutor$1(SubHomeCommand.scala:120)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at liftF @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$build$4(ContextualExecutorBuilder.scala:153)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$1(ContextualExecutorBuilder.scala:123)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$2(ContextualExecutorBuilder.scala:124)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$1(ContextualExecutorBuilder.scala:123)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at withFilter @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$2(ContextualExecutorBuilder.scala:124)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at map @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$2(ContextualExecutorBuilder.scala:124)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$1(ContextualExecutorBuilder.scala:123)
[Sun, 3. Oct 2021 15:27:23 JST WARN] at flatMap @ com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder.$anonfun$refineSender$1(ContextualExecutorBuilder.scala:123)
```

**Comment by KisaragiEffective** [comment]
https://www.db-fiddle.com/f/AYqRpToVLGyf7sCpdonqY/0

単純にupsert節の`values`が要らなさそう
