### ISSUE TITLE
PlayerPickupItemListener.onPickupMineStackItemでNoSuchElementException

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1430]
```
[12:04:34] [Server thread/ERROR]: Could not pass event PlayerPickupItemEvent to SeichiAssist v35
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityItem.d(EntityItem.java:331) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityHuman.c(EntityHuman.java:418) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:393) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:313) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:408) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1106) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:319) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.util.NoSuchElementException: key not found: 69984845-7104-4183-a505-323d5d340cd2
	at scala.collection.MapOps.default(Map.scala:246) ~[?:?]
	at scala.collection.MapOps.default$(Map.scala:245) ~[?:?]
	at scala.collection.AbstractMap.default(Map.scala:376) ~[?:?]
	at scala.collection.mutable.HashMap.apply(HashMap.scala:405) ~[?:?]
	at com.github.unchama.seichiassist.listener.PlayerPickupItemListener.onPickupMineStackItem(PlayerPickupItemListener.scala:21) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	... 18 more

```

**Comment by Lucky3028** [comment]
これ、lost connectionした直後に起きてるっぽいです。それと、5/1から発生していません。
