### ISSUE TITLE
VotingFairyListenerにおけるIllegalArgumentException

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#160]
```
[14:05:08 WARN]: [SeichiAssist] Task #17 for SeichiAssist v1.1.1 generated an ex
ception
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_212]
        at com.github.unchama.seichiassist.listener.VotingFairyListener.regeneMa
na(VotingFairyListener.java:140) ~[?:?]
        at com.github.unchama.seichiassist.task.VotingFairyTaskRunnable.run(Voti
ngFairyTaskRunnable.java:27) ~[?:?]
        at com.github.unchama.seichiassist.task.MinuteTaskRunnable.run(MinuteTas
kRunnable.java:271) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/058882567e1ce8f2fc39d3ce11696126401bde39/src/main/java/com/github/unchama/seichiassist/listener/VotingFairyListener.java#L140

**Comment by karayuumac** [comment]
これが原因で採掘速度上昇効果の付与・ガチャ券付与が行われていない可能性があるので優先度は高め。

**Comment by KisaragiEffective** [comment]
maybe fixed
