### ISSUE TITLE
期限切れ保護自動削除コマンド(rmp)が動作しない

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#292]
/rmp remove world_SW_2 7
```
[11:17:29] [Server thread/WARN]: java.lang.ClassCastException: java.lang.Integer cannot be cast to org.bukkit.World
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.seichiassist.commands.RmpCommand$removeExecutor$1.invokeSuspend(RmpCommand.kt:65)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.seichiassist.commands.RmpCommand$removeExecutor$1.invoke(RmpCommand.kt)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.contextualexecutor.builder.ContextualExecutorBuilder$build$1.executeWith(ContextualExecutorBuilder.kt:135)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.contextualexecutor.executors.BranchedExecutor.executeWith(BranchedExecutor.kt:22)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.contextualexecutor.ContextualExecutorKt$asNonBlockingTabExecutor$1$onCommand$1$1$1$1.invokeSuspend(ContextualExecutor.kt:44)
[11:17:29] [Server thread/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[11:17:29] [Server thread/WARN]: 	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.typeclasses.suspended.FxSyntax$effect$1.invoke(FxSyntax.kt:41)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.typeclasses.suspended.FxSyntax$effect$1.invoke(FxSyntax.kt:19)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.extensions.IOConcurrent$async$1.invoke(io.kt:135)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.extensions.IOConcurrent$async$1.invoke(io.kt:120)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.IO$Companion$async$1.invoke(IO.kt:40)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.IO$Companion$async$1.invoke(IO.kt:26)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.IORunLoop.loop(IORunLoop.kt:220)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.IORunLoop.start(IORunLoop.kt:21)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.IO.unsafeRunAsync(IO.kt:120)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.extensions.IOUnsafeRun$DefaultImpls.runNonBlocking(io.kt:192)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.extensions.io.unsafeRun.IOUnsafeRunKt$unsafeRun$1.runNonBlocking(IOUnsafeRun.kt:38)
[11:17:29] [Server thread/WARN]: 	at arrow.effects.extensions.io.unsafeRun.IOUnsafeRunKt.runNonBlocking(IOUnsafeRun.kt:35)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.contextualexecutor.ContextualExecutorKt$asNonBlockingTabExecutor$1$onCommand$1.invokeSuspend(ContextualExecutor.kt:42)
[11:17:29] [Server thread/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[11:17:29] [Server thread/WARN]: 	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:128)
[11:17:29] [Server thread/WARN]: 	at arrow.unsafe.invoke(unsafe.kt:31)
[11:17:29] [Server thread/WARN]: 	at com.github.unchama.contextualexecutor.ContextualExecutorKt$asNonBlockingTabExecutor$1.onCommand(ContextualExecutor.kt:41)
[11:17:29] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:17:29] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:17:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[11:17:29] [Server thread/WARN]: 	at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:93)
[11:17:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[11:17:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[11:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[11:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[11:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[11:17:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[11:17:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/0945026a8f64c68897349712e60d40df39aece72/src/main/java/com/github/unchama/seichiassist/commands/RmpCommand.kt#L65

**Comment by kory33** [comment]
Scala-ize時に修正済み
