### ISSUE TITLE
スケジューラーが止まってしまう

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#301]
原因はこれ。
```
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at com.github.unchama.seichiassist.listener.VotingFairyListener.regeneMana(VotingFairyListener.java:135)
    at com.github.unchama.seichiassist.task.VotingFairyTask.run(VotingFairyTask.java:25)
    at com.github.unchama.seichiassist.task.PlayerDataPeriodicRecalculation.runRoutine(PlayerDataPeriodicRecalculation.kt:175)
    at com.github.unchama.seichiassist.task.RepeatedTaskLauncher.launch(RepeatedTaskLauncher.kt:10)
    at com.github.unchama.seichiassist.task.RepeatedTaskLauncher$launch$1.invokeSuspend(RepeatedTaskLauncher.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:67)
    at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:309)

```

**Comment by karayuumac** [comment]
なるほど...
一応、Issue・PRの題名を変えておきました。
