### ISSUE TITLE
Minestack関連で何らかのエラーが出ている

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#351]
```
[Thu, 21. Nov 2019 19:42:56 JST INFO] Buttonの副作用の非同期実行中にエラーが発生しました.
[Thu, 21. Nov 2019 19:42:56 JST WARN] java.lang.IllegalArgumentException: Cannot drop AIR.
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:292)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:334)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.seichiassist.util.Util$.dropItem(Util.scala:104)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.seichiassist.util.Util$.$anonfun$addItemToPlayerSafely$1(Util.scala:96)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at java.util.HashMap$Values.forEach(HashMap.java:981)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.seichiassist.util.Util$.addItemToPlayerSafely(Util.scala:96)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.seichiassist.menus.minestack.MineStackButtons.$anonfun$withDrawOneStackEffect$2(MineStackButtons.scala:116)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.targetedeffect.UnfocusedEffect$.$anonfun$apply$1(UnfocusedEffect.scala:6)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.targetedeffect.UnfocusedEffect$.$anonfun$apply$1$adapted(UnfocusedEffect.scala:6)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.targetedeffect.package$.$anonfun$delay$2(package.scala:18)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.IO.unsafeRunAsync(IO.scala:257)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.IO.$anonfun$runAsync$1(IO.scala:177)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.IO.unsafeRunTimed(IO.scala:320)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at cats.effect.IO.unsafeRunSync(IO.scala:239)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at com.github.unchama.menuinventory.MenuHandler$.onInventoryClick(MenuHandler.scala:38)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[Thu, 21. Nov 2019 19:42:56 JST WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
```

**Comment by kory33** [comment]
ひとまずfixed by 1c845367.
