### ISSUE TITLE
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#407]
```
[22:49:50] [Server thread/ERROR]: Could not load 'plugins\SeichiAssist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 1, column 7:
    name: @name@
          ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:421) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:228) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 5 more
```

**Comment by kory33** [comment]
fixed by a55b6178.
