### ISSUE TITLE
投票特典付与処理に失敗(/gacha)

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#416]
```
[00:02:46] [Server thread/INFO]: (player name) voted at 2020-01-25 00:02:32 +0900.
[00:02:46] [Server thread/ERROR]: Could not pass event VotifierEvent to SimpleVoteListener v2.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.vexsoftware.votifier.net.VoteReceiver$1.run(VoteReceiver.java:182) [votifier-1.9.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'gacha' in plugin SeichiAssist v1.2.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at me.puyttre.svl.SimpleVoteListener.initOfflineVote(SimpleVoteListener.java:85) ~[?:?]
	at me.puyttre.svl.SimpleVoteListener.vote(SimpleVoteListener.java:63) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 11 more
Caused by: java.lang.NullPointerException
	at com.github.unchama.seichiassist.SeichiAssist.onCommand(SeichiAssist.scala:245) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at me.puyttre.svl.SimpleVoteListener.initOfflineVote(SimpleVoteListener.java:85) ~[?:?]
	at me.puyttre.svl.SimpleVoteListener.vote(SimpleVoteListener.java:63) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 11 more
```

**Comment by KisaragiEffective** [comment]
NPE

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/8b7517ffbf5b6cfbaaeb8ffd98125ae027cfce3b/src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala#L245

**Comment by unchama** [comment]
seichiassistの前提プラグインが投票受付専用サーバに入っておらず、onEnableの処理が中途停止していたのが原因でした。。。

**Comment by unchama** [comment]
☝️1.4.8リリースで再発したけど原因が全く同じだった。（前提プラグインとconfig.ymlの記載内容が増えた）
投票受付専用鯖にもちゃんとリリース作業してもろて
