### ISSUE TITLE
ブロック破壊時の統計更新が異常系を踏む

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#482]
詳細は不明

```
[Mon, 30. Mar 2020 13:50:54 JST WARN] java.lang.IllegalArgumentException: The supplied Material does not have a corresponding statistic
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:662)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.incrementStatistic(CraftPlayer.java:669)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.incrementStatistic(CraftPlayer.java:648)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at com.github.unchama.seichiassist.util.BreakUtil$.$anonfun$massBreakBlock$22(BreakUtil.scala:264)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at com.github.unchama.seichiassist.util.BreakUtil$.$anonfun$massBreakBlock$22$adapted(BreakUtil.scala:264)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at scala.collection.immutable.List.foreach(List.scala:305)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at com.github.unchama.seichiassist.util.BreakUtil$.$anonfun$massBreakBlock$18(BreakUtil.scala:264)
[Mon, 30. Mar 2020 13:50:54 JST WARN]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

**Comment by KisaragiEffective** [comment]
破壊したブロックに紐づく統計が存在しないことによる例外; エンドフレームあたり？

**Comment by kory33** [comment]
ブロックのロックが取れていないっぽい
走査して破壊をキューするときにすべてロックを書けているはずですがこのロックが動いていない箇所があってそこでエラーが出ています

```
[Thu, 2. Apr 2020 08:17:05 JST WARN] AIRの破壊統計のインクリメントに失敗しました。
[Thu, 2. Apr 2020 08:17:05 JST WARN] AIRの破壊統計のインクリメントに失敗しました。
[Thu, 2. Apr 2020 08:17:05 JST WARN] AIRの破壊統計のインクリメントに失敗しました。
[Thu, 2. Apr 2020 08:17:05 JST WARN] AIRの破壊統計のインクリメントに失敗しました。
[Thu, 2. Apr 2020 08:17:05 JST INFO] 単爆破壊エフェクトを再生する最中にエラーが発生しました。
```

**Comment by kory33** [comment]
❌  二人が同じ領域を整地するときのロックを取っていない

**Comment by kory33** [comment]
相互ロックを取ってないのが原因っぽかったです
fixed by a7de727.
