### ISSUE TITLE
経験値瓶割りのケース漏れ

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#483]
```
spigota_1     | [13:19:27 ERROR]: Could not pass event PlayerInteractEvent to SeichiAssist v1.2.12
spigota_1     | org.bukkit.event.EventException: null
spigota_1     |         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
spigota_1     |         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
spigota_1     |         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
spigota_1     | Caused by: java.lang.NullPointerException
spigota_1     |         at com.github.unchama.seichiassist.listener.PlayerClickListener.onPlayerRightClickExpBottleEvent(PlayerClickListener.scala:455) ~[?:?]
spigota_1     |         at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
spigota_1     |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
spigota_1     |         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
spigota_1     |         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
spigota_1     |         ... 17 more
```

**Comment by KisaragiEffective** [comment]
ｶﾞｯ
