### ISSUE TITLE
二つ名システムに入るボタンをぶち壊した

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#751]

**Comment by unchama** [comment]
```
[21:29:02] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SeichiAssist v1.5.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: scala.MatchError: dØÌ_j
[ (of class java.lang.String)
	at com.github.unchama.seichiassist.listener.invlistener.OnClickTitleMenu$.onPlayerClickTitleMenuEvent(OnClickTitleMenu.scala:70) ~[?:?]
	at com.github.unchama.seichiassist.listener.PlayerInventoryListener.onPlayerClickTitleMenuEvent(PlayerInventoryListener.scala:384) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	... 15 more
```

**Comment by KisaragiEffective** [comment]
肝心なところが文字化け :cry:

**Comment by KisaragiEffective** [comment]
わかった！
matchがexhausiveじゃないからscalaがランタイムでキレて例外を吐いた

**Comment by KisaragiEffective** [comment]
まだ治ってない :cry:

**Comment by KisaragiEffective** [comment]
例外は起きていないのでロジックミスと考えられるが…

**Comment by KisaragiEffective** [comment]
***\*HELP WANTED\****

**Comment by stouma915** [comment]
いろいろやってみるマン(唐突)

**Comment by stouma915** [comment]
![image](https://user-images.githubusercontent.com/62248740/98112415-85703700-1ee5-11eb-90e3-de534bddf6b3.png)
木の棒メニューのどのボタンを押してもそれ以外のインベントリってことになってました(既知かもしれない)

**Comment by KisaragiEffective** [comment]
(それは私が #752 で書きました)
イベントをキャンセルしているわけではないので木の棒メニューのハンドラに制御が渡って二つ名メニューを開くのが想定してた動作なんですが、どうもそうならない

**Comment by stouma915** [comment]
`@EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)`
を木の棒メニューのハンドラに追加したりしても変わりませんか？

**Comment by KisaragiEffective** [comment]
**素の**BukkitのEventHandlerではないので意味がなさそう

**Comment by KisaragiEffective** [comment]
@kory33 please help me with that

**Comment by stouma915** [comment]
![image](https://user-images.githubusercontent.com/62248740/98114103-17793f00-1ee8-11eb-98a8-9ccd091b696b.png)
ここコメントアウトしたら正常に動きました
コメントアウトしてもなんかアイテム取れるとかそうゆうことは起きてないのでどっかで既にキャンセルされてる説(適当)

**Comment by KisaragiEffective** [comment]
それは上と同じファイルですか？

**Comment by stouma915** [comment]
はい

**Comment by KisaragiEffective** [comment]
完全に理解してしまった
これはあれだ、matchに書き換えたときにevent.setCancelledを移し忘れた！
