### ISSUE TITLE
保存処理時に存在しないプレーヤーを参照しようとしてNPEを吐く

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#893]
```
[月, 25. 1 2021 17:03:51 JST WARN] java.lang.NullPointerException
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.data.player.PlayerData.$anonfun$updateAndCalcMinedBlockAmount$1(PlayerData.scala:489)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.data.player.PlayerData.$anonfun$updateAndCalcMinedBlockAmount$1$adapted(PlayerData.scala:488)
[月, 25. 1 2021 17:03:51 JST WARN] at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
[月, 25. 1 2021 17:03:51 JST WARN] at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
[月, 25. 1 2021 17:03:51 JST WARN] at scala.collection.immutable.HashSet.map(HashSet.scala:34)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.data.player.PlayerData.updateAndCalcMinedBlockAmount(PlayerData.scala:488)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.data.player.PlayerData.updateOnQuit(PlayerData.scala:465)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.SeichiAssist.$anonfun$bungeeSemaphoreResponderSystem$3(SeichiAssist.scala:185)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.SeichiAssist.$anonfun$bungeeSemaphoreResponderSystem$3$adapted(SeichiAssist.scala:185)
[月, 25. 1 2021 17:03:51 JST WARN] at scala.util.ChainingOps$.tap$extension(ChainingOps.scala:38)
[月, 25. 1 2021 17:03:51 JST WARN] at com.github.unchama.seichiassist.SeichiAssist.$anonfun$bungeeSemaphoreResponderSystem$2(SeichiAssist.scala:185)
[月, 25. 1 2021 17:03:51 JST WARN] at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
[月, 25. 1 2021 17:03:51 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
[月, 25. 1 2021 17:03:51 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
[月, 25. 1 2021 17:03:51 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
[月, 25. 1 2021 17:03:51 JST WARN] at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
[月, 25. 1 2021 17:03:51 JST WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[月, 25. 1 2021 17:03:51 JST WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[月, 25. 1 2021 17:03:51 JST WARN] at java.lang.Thread.run(Thread.java:748)
```

ここで参照されている `player` はメソッドであり、呼び出された時点でBukkitにクエリするのでPlayerDataの保存処理がプレーヤー退出後に行われるとNPEを吐いて保存処理が死ぬ

**Comment by kory33** [comment]
`updateAndCalcMinedBlockAmount` については #894 で直しますが、それ以外も直すべきぽい

**Comment by kory33** [comment]
fixed by 8342795
